// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WTVersus.Models;

namespace WTVersus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200531102342_AddTrackingOpticalDevice")]
    partial class AddTrackingOpticalDevice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WTVersus.Models.Heli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AAMCount")
                        .HasColumnType("int");

                    b.Property<bool>("AAMissile")
                        .HasColumnType("bit");

                    b.Property<int?>("AGMArmorPenetration")
                        .HasColumnType("int");

                    b.Property<int?>("AGMCount")
                        .HasColumnType("int");

                    b.Property<int?>("AGMRange")
                        .HasColumnType("int");

                    b.Property<int?>("AGMSpeed")
                        .HasColumnType("int");

                    b.Property<bool>("AGMissile")
                        .HasColumnType("bit");

                    b.Property<int?>("ASMCount")
                        .HasColumnType("int");

                    b.Property<bool>("ASMissile")
                        .HasColumnType("bit");

                    b.Property<bool>("AirRadar")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoAGMissile")
                        .HasColumnType("bit");

                    b.Property<double?>("BR")
                        .HasColumnType("float");

                    b.Property<bool>("Bomb")
                        .HasColumnType("bit");

                    b.Property<int?>("BombLoad")
                        .HasColumnType("int");

                    b.Property<bool>("CCIP")
                        .HasColumnType("bit");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClimbTo1000")
                        .HasColumnType("int");

                    b.Property<int?>("EnginePower")
                        .HasColumnType("int");

                    b.Property<int?>("FirstFlyYear")
                        .HasColumnType("int");

                    b.Property<bool>("FixedCannon")
                        .HasColumnType("bit");

                    b.Property<bool>("Flares")
                        .HasColumnType("bit");

                    b.Property<bool>("GroundRadar")
                        .HasColumnType("bit");

                    b.Property<bool>("HIRSS")
                        .HasColumnType("bit");

                    b.Property<bool>("IRCM")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaserDesignator")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OffensiveWeapon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OpticalTracking")
                        .HasColumnType("bit");

                    b.Property<bool>("RWR")
                        .HasColumnType("bit");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RepairCost")
                        .HasColumnType("int");

                    b.Property<bool>("ThermalGunner")
                        .HasColumnType("bit");

                    b.Property<int?>("Turn360")
                        .HasColumnType("int");

                    b.Property<bool>("TurningCannon")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.Property<string>("WikiDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Helis");
                });

            modelBuilder.Entity("WTVersus.Models.Plane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AAMissile")
                        .HasColumnType("bit");

                    b.Property<bool>("AGMissile")
                        .HasColumnType("bit");

                    b.Property<bool>("ASMissile")
                        .HasColumnType("bit");

                    b.Property<bool>("AirBrake")
                        .HasColumnType("bit");

                    b.Property<bool>("AirRadar")
                        .HasColumnType("bit");

                    b.Property<double?>("BR")
                        .HasColumnType("float");

                    b.Property<int?>("BombLoad")
                        .HasColumnType("int");

                    b.Property<double?>("BurstMass")
                        .HasColumnType("float");

                    b.Property<bool>("CCIP")
                        .HasColumnType("bit");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Climb")
                        .HasColumnType("int");

                    b.Property<string>("CourseWeapon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnginePower")
                        .HasColumnType("int");

                    b.Property<int?>("FirstFlyYear")
                        .HasColumnType("int");

                    b.Property<bool>("Flares")
                        .HasColumnType("bit");

                    b.Property<int?>("Flutter")
                        .HasColumnType("int");

                    b.Property<bool>("GSuit")
                        .HasColumnType("bit");

                    b.Property<bool>("GroundRadar")
                        .HasColumnType("bit");

                    b.Property<bool>("HBomb")
                        .HasColumnType("bit");

                    b.Property<bool>("HCannon")
                        .HasColumnType("bit");

                    b.Property<bool>("HTorpedo")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxSpeedAt0")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSpeedAt5000")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OptimalAilerons")
                        .HasColumnType("int");

                    b.Property<int?>("OptimalAlitude")
                        .HasColumnType("int");

                    b.Property<int?>("OptimalElevator")
                        .HasColumnType("int");

                    b.Property<bool>("Parachute")
                        .HasColumnType("bit");

                    b.Property<bool>("RWR")
                        .HasColumnType("bit");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RepairCost")
                        .HasColumnType("int");

                    b.Property<bool>("Tailhook")
                        .HasColumnType("bit");

                    b.Property<double?>("TurnAt0")
                        .HasColumnType("float");

                    b.Property<bool>("Turrel")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.Property<string>("WikiDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WrongMusic")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("WTVersus.Models.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AAMachineGun")
                        .HasColumnType("bit");

                    b.Property<int?>("AccelerationTo100")
                        .HasColumnType("int");

                    b.Property<bool>("AddOnArmor")
                        .HasColumnType("bit");

                    b.Property<bool>("AirLockRadar")
                        .HasColumnType("bit");

                    b.Property<bool>("AirSearchRadar")
                        .HasColumnType("bit");

                    b.Property<bool>("Amphibious")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoLoader")
                        .HasColumnType("bit");

                    b.Property<double?>("BR")
                        .HasColumnType("float");

                    b.Property<string>("Cannon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DownAimAngle")
                        .HasColumnType("int");

                    b.Property<int?>("EnginePower")
                        .HasColumnType("int");

                    b.Property<bool>("ExhaustSmoke")
                        .HasColumnType("bit");

                    b.Property<int?>("FirstRideYear")
                        .HasColumnType("int");

                    b.Property<bool>("GrenadeSmoke")
                        .HasColumnType("bit");

                    b.Property<bool>("HullBreak")
                        .HasColumnType("bit");

                    b.Property<bool>("Hydropneumatic")
                        .HasColumnType("bit");

                    b.Property<bool>("IRSpotlight")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxReverseSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSpeedAtRoad")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSpeedAtTerrain")
                        .HasColumnType("int");

                    b.Property<bool>("NVDCommander")
                        .HasColumnType("bit");

                    b.Property<bool>("NVDGunner")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Penetration")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReactiveArmor")
                        .HasColumnType("bit");

                    b.Property<int?>("ReducedArmorBottomSheet")
                        .HasColumnType("int");

                    b.Property<int?>("ReducedArmorFrontTurret")
                        .HasColumnType("int");

                    b.Property<int?>("ReducedArmorTopSheet")
                        .HasColumnType("int");

                    b.Property<double?>("ReloadTime")
                        .HasColumnType("float");

                    b.Property<int?>("RepairCost")
                        .HasColumnType("int");

                    b.Property<bool>("ShellAP")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellAPCR")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellAPDS")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellAPFSDS")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellAPHE")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellATGM")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellHE")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellHEAT")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellHEATFS")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellHEATGRENADE")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellHESH")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellHEVT")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellSAM")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellSSM")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellShrapnel")
                        .HasColumnType("bit");

                    b.Property<bool>("ShellSmoke")
                        .HasColumnType("bit");

                    b.Property<int?>("ShellSpeed")
                        .HasColumnType("int");

                    b.Property<bool>("Stabilizer")
                        .HasColumnType("bit");

                    b.Property<bool>("ThermalCommander")
                        .HasColumnType("bit");

                    b.Property<bool>("ThermalGunner")
                        .HasColumnType("bit");

                    b.Property<int?>("TurnHullTime")
                        .HasColumnType("int");

                    b.Property<int?>("TurnTurretTime")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpAimAngle")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<string>("WikiDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tanks");
                });
#pragma warning restore 612, 618
        }
    }
}
